name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  database_name:  # id of input
    description: 'The name of the database'
    required: true
  parent_branch_name:
    description: 'The name of the parent branch'
    required: true
  branch_name:
    description: 'The name of the new branch'
    required: true
  org_name:
    description: 'The name of the organization that owns the database'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'